#Teste
name: Test Workflow

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Testando GitHub Actions
        run: echo "GitHub Actions está funcionando!"
